# AUTO-GENERATED by scripts/oas-sync emit-models exercise_diary. Do not edit by hand.
"""Pydantic response models for the FatSecret ``exercise_diary`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Optional

from pydantic import Field

from .._common import _FS_Base


class Day(_FS_Base):
    """Generated from XSD ``day``."""

    date_int: int
    calories: Optional[Decimal] = Field(default=None)
    carbohydrate: Optional[Decimal] = Field(default=None)
    protein: Optional[Decimal] = Field(default=None)
    fat: Optional[Decimal] = Field(default=None)
    weight_kg: Optional[Decimal] = Field(default=None)
    weight_comment: Optional[str] = Field(default=None)


class Exercise(_FS_Base):
    """Generated from XSD ``exercise``."""

    exercise_id: int
    exercise_name: str


class ExerciseEntry(_FS_Base):
    """Generated from XSD ``exercise_entry``."""

    is_template_value: bool
    exercise_id: int
    exercise_name: str
    minutes: int
    calories: Decimal


class ExerciseEntries(_FS_Base):
    """Generated from XSD ``exercise_entries``."""

    exercise_entry: List[ExerciseEntry]


class ExerciseTypes(_FS_Base):
    """Generated from XSD ``exercise_types``."""

    exercise: List[Exercise]


class Month(_FS_Base):
    """Generated from XSD ``month``."""

    from_date_int: int
    to_date_int: int
    day: Optional[List[Day]] = Field(default=None)
