# AUTO-GENERATED by scripts/oas-sync emit-models foods. Do not edit by hand.
"""Pydantic response models for the FatSecret ``foods`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Literal, Optional

from pydantic import Field

from .._common import _FS_Base, FoodType, Ternary


class Allergen(_FS_Base):
    """Generated from XSD ``allergen``."""

    id: Optional[int] = Field(default=None)
    name: Optional[str] = Field(default=None)
    value: Optional[Ternary] = Field(default=None)


class FoodEntry(_FS_Base):
    """Generated from XSD ``food_entry``."""

    food_entry_id: Optional[int] = Field(default=None)
    food_entry_description: Optional[str] = Field(default=None)
    date_int: Optional[int] = Field(default=None)
    meal: Optional[Literal['Breakfast', 'Lunch', 'Dinner', 'Other']] = Field(default=None)
    food_id: Optional[int] = Field(default=None)
    serving_id: Optional[int] = Field(default=None)
    number_of_units: Optional[Decimal] = Field(default=None)
    food_entry_name: Optional[str] = Field(default=None)
    calories: Optional[Decimal] = Field(default=None)
    carbohydrate: Optional[Decimal] = Field(default=None)
    protein: Optional[Decimal] = Field(default=None)
    fat: Optional[Decimal] = Field(default=None)
    saturated_fat: Optional[Decimal] = Field(default=None)
    polyunsaturated_fat: Optional[Decimal] = Field(default=None)
    monounsaturated_fat: Optional[Decimal] = Field(default=None)
    trans_fat: Optional[Decimal] = Field(default=None)
    cholesterol: Optional[Decimal] = Field(default=None)
    sodium: Optional[Decimal] = Field(default=None)
    potassium: Optional[Decimal] = Field(default=None)
    fiber: Optional[Decimal] = Field(default=None)
    sugar: Optional[Decimal] = Field(default=None)
    vitamin_a: Optional[Decimal] = Field(default=None)
    vitamin_c: Optional[Decimal] = Field(default=None)
    calcium: Optional[Decimal] = Field(default=None)
    iron: Optional[Decimal] = Field(default=None)


class FoodFoodSubCategories(_FS_Base):
    """Generated from XSD ``<inline FoodFoodSubCategories>``."""

    food_sub_category: Optional[List[str]] = Field(default=None)


class FoodImage(_FS_Base):
    """Generated from XSD ``food_image``."""

    image_url: Optional[str] = Field(default=None)
    image_type: Optional[int] = Field(default=None)


class FoodSubCategories(_FS_Base):
    """Generated from XSD ``food_sub_categories``."""

    food_sub_category: Optional[str] = Field(default=None)


class Preference(_FS_Base):
    """Generated from XSD ``preference``."""

    id: Optional[int] = Field(default=None)
    name: Optional[str] = Field(default=None)
    value: Optional[Ternary] = Field(default=None)


class Serving(_FS_Base):
    """Generated from XSD ``serving``."""

    serving_id: Optional[int] = Field(default=None)
    serving_description: Optional[str] = Field(default=None)
    serving_url: Optional[str] = Field(default=None)
    metric_serving_amount: Optional[Decimal] = Field(default=None)
    metric_serving_unit: Optional[str] = Field(default=None)
    number_of_units: Optional[Decimal] = Field(default=None)
    measurement_description: Optional[str] = Field(default=None)
    is_default: Optional[bool] = Field(default=None)
    calories: Optional[Decimal] = Field(default=None)
    carbohydrate: Optional[Decimal] = Field(default=None)
    protein: Optional[Decimal] = Field(default=None)
    fat: Optional[Decimal] = Field(default=None)
    saturated_fat: Optional[Decimal] = Field(default=None)
    polyunsaturated_fat: Optional[Decimal] = Field(default=None)
    monounsaturated_fat: Optional[Decimal] = Field(default=None)
    trans_fat: Optional[Decimal] = Field(default=None)
    cholesterol: Optional[Decimal] = Field(default=None)
    sodium: Optional[Decimal] = Field(default=None)
    potassium: Optional[Decimal] = Field(default=None)
    fiber: Optional[Decimal] = Field(default=None)
    sugar: Optional[Decimal] = Field(default=None)
    added_sugars: Optional[Decimal] = Field(default=None)
    vitamin_d: Optional[Decimal] = Field(default=None)
    vitamin_a: Optional[Decimal] = Field(default=None)
    vitamin_c: Optional[Decimal] = Field(default=None)
    calcium: Optional[Decimal] = Field(default=None)
    iron: Optional[Decimal] = Field(default=None)


class Allergens(_FS_Base):
    """Generated from XSD ``allergens``."""

    allergen: Optional[Allergen] = Field(default=None)


class FoodEntries(_FS_Base):
    """Generated from XSD ``food_entries``."""

    food_entry: Optional[List[FoodEntry]] = Field(default=None)


class FoodFoodImages(_FS_Base):
    """Generated from XSD ``<inline FoodFoodImages>``."""

    food_image: Optional[List[FoodImage]] = Field(default=None)


class FoodImages(_FS_Base):
    """Generated from XSD ``food_images``."""

    food_image: Optional[FoodImage] = Field(default=None)


class FoodServings(_FS_Base):
    """Generated from XSD ``<inline FoodServings>``."""

    serving: Optional[List[Serving]] = Field(default=None)


class Preferences(_FS_Base):
    """Generated from XSD ``preferences``."""

    preference: Optional[Preference] = Field(default=None)


class FoodAttributes(_FS_Base):
    """Generated from XSD ``food_attributes``."""

    preferences: Optional[Preferences] = Field(default=None)


class Food(_FS_Base):
    """Generated from XSD ``food``."""

    food_id: Optional[int] = Field(default=None)
    food_name: Optional[str] = Field(default=None)
    brand_name: Optional[str] = Field(default=None)
    food_type: Optional[FoodType] = Field(default=None)
    food_url: Optional[str] = Field(default=None)
    food_description: Optional[str] = Field(default=None)
    servings: Optional[FoodServings] = Field(default=None)
    food_sub_categories: Optional[FoodFoodSubCategories] = Field(default=None)
    food_images: Optional[FoodFoodImages] = Field(default=None)
    food_attributes: Optional[FoodAttributes] = Field(default=None)


class FoodResults(_FS_Base):
    """Generated from XSD ``food_results``."""

    food: Optional[List[Food]] = Field(default=None)


class Foods(_FS_Base):
    """Generated from XSD ``foods``."""

    max_results: Optional[int] = Field(default=None)
    total_results: Optional[int] = Field(default=None)
    page_number: Optional[int] = Field(default=None)
    food: Optional[List[Food]] = Field(default=None)


class FoodsSearchResults(_FS_Base):
    """Generated from XSD ``<inline FoodsSearchResults>``."""

    food: Optional[List[Food]] = Field(default=None)


class FoodsSearch(_FS_Base):
    """Generated from XSD ``foods_search``."""

    max_results: Optional[int] = Field(default=None)
    total_results: Optional[int] = Field(default=None)
    page_number: Optional[int] = Field(default=None)
    results: Optional[FoodsSearchResults] = Field(default=None)
