# AUTO-GENERATED by scripts/oas-sync emit-models food_diary. Do not edit by hand.
"""Pydantic response models for the FatSecret ``food_diary`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Literal, Optional

from pydantic import Field

from .._common import _FS_Base


class Day(_FS_Base):
    """Generated from XSD ``day``."""

    date_int: int
    calories: Optional[Decimal] = Field(default=None)
    carbohydrate: Optional[Decimal] = Field(default=None)
    protein: Optional[Decimal] = Field(default=None)
    fat: Optional[Decimal] = Field(default=None)
    weight_kg: Optional[Decimal] = Field(default=None)
    weight_comment: Optional[str] = Field(default=None)


class FoodEntry(_FS_Base):
    """Generated from XSD ``food_entry``."""

    food_entry_id: int
    food_entry_description: str
    date_int: int
    meal: Literal['Breakfast', 'Lunch', 'Dinner', 'Other']
    food_id: int
    serving_id: int
    number_of_units: Decimal
    food_entry_name: str
    calories: Decimal
    carbohydrate: Decimal
    protein: Decimal
    fat: Decimal
    saturated_fat: Optional[Decimal] = Field(default=None)
    polyunsaturated_fat: Optional[Decimal] = Field(default=None)
    monounsaturated_fat: Optional[Decimal] = Field(default=None)
    trans_fat: Optional[Decimal] = Field(default=None)
    cholesterol: Optional[Decimal] = Field(default=None)
    sodium: Optional[Decimal] = Field(default=None)
    potassium: Optional[Decimal] = Field(default=None)
    fiber: Optional[Decimal] = Field(default=None)
    sugar: Optional[Decimal] = Field(default=None)
    vitamin_a: Optional[Decimal] = Field(default=None)
    vitamin_c: Optional[Decimal] = Field(default=None)
    calcium: Optional[Decimal] = Field(default=None)
    iron: Optional[Decimal] = Field(default=None)


class FoodEntries(_FS_Base):
    """Generated from XSD ``food_entries``."""

    food_entry: Optional[List[FoodEntry]] = Field(default=None)


class Month(_FS_Base):
    """Generated from XSD ``month``."""

    from_date_int: int
    to_date_int: int
    day: Optional[List[Day]] = Field(default=None)
