# AUTO-GENERATED by scripts/oas-sync emit-models foods. Do not edit by hand.
"""Pydantic response models for the FatSecret ``foods`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Literal, Optional

from pydantic import Field

from .._common import _FS_Base, FoodType, Ternary


class Allergen(_FS_Base):
    """Generated from XSD ``allergen``."""

    id: int
    name: str
    value: Ternary


class FoodEntry(_FS_Base):
    """Generated from XSD ``food_entry``."""

    food_entry_id: int
    food_entry_description: str
    date_int: int
    meal: Literal['Breakfast', 'Lunch', 'Dinner', 'Other']
    food_id: int
    serving_id: int
    number_of_units: Decimal
    food_entry_name: str
    calories: Decimal
    carbohydrate: Decimal
    protein: Decimal
    fat: Decimal
    saturated_fat: Optional[Decimal] = Field(default=None)
    polyunsaturated_fat: Optional[Decimal] = Field(default=None)
    monounsaturated_fat: Optional[Decimal] = Field(default=None)
    trans_fat: Optional[Decimal] = Field(default=None)
    cholesterol: Optional[Decimal] = Field(default=None)
    sodium: Optional[Decimal] = Field(default=None)
    potassium: Optional[Decimal] = Field(default=None)
    fiber: Optional[Decimal] = Field(default=None)
    sugar: Optional[Decimal] = Field(default=None)
    vitamin_a: Optional[Decimal] = Field(default=None)
    vitamin_c: Optional[Decimal] = Field(default=None)
    calcium: Optional[Decimal] = Field(default=None)
    iron: Optional[Decimal] = Field(default=None)


class FoodFoodSubCategories(_FS_Base):
    """Generated from XSD ``<inline FoodFoodSubCategories>``."""

    food_sub_category: List[str]


class FoodImage(_FS_Base):
    """Generated from XSD ``food_image``."""

    image_url: str
    image_type: int


class FoodSubCategories(_FS_Base):
    """Generated from XSD ``food_sub_categories``."""

    food_sub_category: str


class Preference(_FS_Base):
    """Generated from XSD ``preference``."""

    id: int
    name: str
    value: Ternary


class Serving(_FS_Base):
    """Generated from XSD ``serving``."""

    serving_id: int
    serving_description: str
    serving_url: str
    metric_serving_amount: Optional[Decimal] = Field(default=None)
    metric_serving_unit: Optional[str] = Field(default=None)
    number_of_units: Decimal
    measurement_description: str
    is_default: bool
    calories: Decimal
    carbohydrate: Decimal
    protein: Decimal
    fat: Decimal
    saturated_fat: Optional[Decimal] = Field(default=None)
    polyunsaturated_fat: Optional[Decimal] = Field(default=None)
    monounsaturated_fat: Optional[Decimal] = Field(default=None)
    trans_fat: Optional[Decimal] = Field(default=None)
    cholesterol: Optional[Decimal] = Field(default=None)
    sodium: Optional[Decimal] = Field(default=None)
    potassium: Optional[Decimal] = Field(default=None)
    fiber: Optional[Decimal] = Field(default=None)
    sugar: Optional[Decimal] = Field(default=None)
    added_sugars: Optional[Decimal] = Field(default=None)
    vitamin_d: Optional[Decimal] = Field(default=None)
    vitamin_a: Optional[Decimal] = Field(default=None)
    vitamin_c: Optional[Decimal] = Field(default=None)
    calcium: Optional[Decimal] = Field(default=None)
    iron: Optional[Decimal] = Field(default=None)


class Allergens(_FS_Base):
    """Generated from XSD ``allergens``."""

    allergen: Allergen


class FoodEntries(_FS_Base):
    """Generated from XSD ``food_entries``."""

    food_entry: Optional[List[FoodEntry]] = Field(default=None)


class FoodFoodImages(_FS_Base):
    """Generated from XSD ``<inline FoodFoodImages>``."""

    food_image: List[FoodImage]


class FoodImages(_FS_Base):
    """Generated from XSD ``food_images``."""

    food_image: FoodImage


class FoodServings(_FS_Base):
    """Generated from XSD ``<inline FoodServings>``."""

    serving: List[Serving]


class Preferences(_FS_Base):
    """Generated from XSD ``preferences``."""

    preference: Preference


class FoodAttributes(_FS_Base):
    """Generated from XSD ``food_attributes``."""

    preferences: Preferences


class Food(_FS_Base):
    """Generated from XSD ``food``."""

    food_id: int
    food_name: str
    brand_name: Optional[str] = Field(default=None)
    food_type: FoodType
    food_url: str
    food_description: Optional[str] = Field(default=None)
    servings: Optional[FoodServings] = Field(default=None)
    food_sub_categories: Optional[FoodFoodSubCategories] = Field(default=None)
    food_images: Optional[FoodFoodImages] = Field(default=None)
    food_attributes: Optional[FoodAttributes] = Field(default=None)


class FoodResults(_FS_Base):
    """Generated from XSD ``food_results``."""

    food: Optional[List[Food]] = Field(default=None)


class Foods(_FS_Base):
    """Generated from XSD ``foods``."""

    max_results: int
    total_results: int
    page_number: int
    food: Optional[List[Food]] = Field(default=None)


class FoodsSearchResults(_FS_Base):
    """Generated from XSD ``<inline FoodsSearchResults>``."""

    food: Optional[List[Food]] = Field(default=None)


class FoodsSearch(_FS_Base):
    """Generated from XSD ``foods_search``."""

    max_results: int
    total_results: int
    page_number: int
    results: FoodsSearchResults
