# AUTO-GENERATED by scripts/oas-sync emit-models profile_auth. Do not edit by hand.
"""Pydantic response models for the FatSecret ``profile_auth`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import Literal, Optional

from pydantic import Field

from .._common import _FS_Base


class Profile(_FS_Base):
    """Generated from XSD ``profile``."""

    auth_token: Optional[str] = Field(default=None)
    auth_secret: Optional[str] = Field(default=None)
    weight_measure: Optional[Literal['Kg', 'Lb']] = Field(default=None)
    height_measure: Optional[Literal['Cm', 'Inch']] = Field(default=None)
    last_weight_kg: Optional[Decimal] = Field(default=None)
    last_weight_date_int: Optional[int] = Field(default=None)
    last_weight_comment: Optional[str] = Field(default=None)
    goal_weight_kg: Optional[Decimal] = Field(default=None)
    height_cm: Optional[Decimal] = Field(default=None)
    session_key: Optional[str] = Field(default=None)
