# AUTO-GENERATED by scripts/oas-sync emit-models recipes. Do not edit by hand.
"""Pydantic response models for the FatSecret ``recipes`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Optional

from pydantic import Field

from .._common import _FS_Base


class RecipesRecipeRecipeIngredients(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipeRecipeIngredients>``."""

    ingredient: Optional[List[str]] = Field(default=None)


class RecipesRecipeRecipeNutrition(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipeRecipeNutrition>``."""

    calories: Decimal
    carbohydrate: Decimal
    protein: Decimal
    fat: Decimal


class RecipesRecipeRecipeTypes(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipeRecipeTypes>``."""

    recipe_type: Optional[List[str]] = Field(default=None)


class RecipesRecipe(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipe>``."""

    recipe_id: int
    recipe_name: str
    recipe_description: str
    recipe_image: Optional[str] = Field(default=None)
    recipe_nutrition: Optional[RecipesRecipeRecipeNutrition] = Field(default=None)
    recipe_ingredients: Optional[RecipesRecipeRecipeIngredients] = Field(default=None)
    recipe_types: Optional[RecipesRecipeRecipeTypes] = Field(default=None)


class Recipes(_FS_Base):
    """Generated from XSD ``recipes``."""

    max_results: int
    total_results: int
    page_number: int
    recipe: RecipesRecipe
