# AUTO-GENERATED by scripts/oas-sync emit-models recipes. Do not edit by hand.
"""Pydantic response models for the FatSecret ``recipes`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Optional

from pydantic import Field

from .._common import _FS_Base


class RecipesRecipeRecipeIngredients(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipeRecipeIngredients>``."""

    ingredient: Optional[List[str]] = Field(default=None)


class RecipesRecipeRecipeNutrition(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipeRecipeNutrition>``."""

    calories: Optional[Decimal] = Field(default=None)
    carbohydrate: Optional[Decimal] = Field(default=None)
    protein: Optional[Decimal] = Field(default=None)
    fat: Optional[Decimal] = Field(default=None)


class RecipesRecipeRecipeTypes(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipeRecipeTypes>``."""

    recipe_type: Optional[List[str]] = Field(default=None)


class RecipesRecipe(_FS_Base):
    """Generated from XSD ``<inline RecipesRecipe>``."""

    recipe_id: Optional[int] = Field(default=None)
    recipe_name: Optional[str] = Field(default=None)
    recipe_description: Optional[str] = Field(default=None)
    recipe_image: Optional[str] = Field(default=None)
    recipe_nutrition: Optional[RecipesRecipeRecipeNutrition] = Field(default=None)
    recipe_ingredients: Optional[RecipesRecipeRecipeIngredients] = Field(default=None)
    recipe_types: Optional[RecipesRecipeRecipeTypes] = Field(default=None)


class Recipes(_FS_Base):
    """Generated from XSD ``recipes``."""

    max_results: Optional[int] = Field(default=None)
    total_results: Optional[int] = Field(default=None)
    page_number: Optional[int] = Field(default=None)
    recipe: Optional[RecipesRecipe] = Field(default=None)
