# AUTO-GENERATED by scripts/oas-sync emit-models weight_diary. Do not edit by hand.
"""Pydantic response models for the FatSecret ``weight_diary`` resource (generated from XSD)."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Optional

from pydantic import Field

from .._common import _FS_Base


class Day(_FS_Base):
    """Generated from XSD ``day``."""

    date_int: Optional[int] = Field(default=None)
    calories: Optional[Decimal] = Field(default=None)
    carbohydrate: Optional[Decimal] = Field(default=None)
    protein: Optional[Decimal] = Field(default=None)
    fat: Optional[Decimal] = Field(default=None)
    weight_kg: Optional[Decimal] = Field(default=None)
    weight_comment: Optional[str] = Field(default=None)


class Month(_FS_Base):
    """Generated from XSD ``month``."""

    from_date_int: Optional[int] = Field(default=None)
    to_date_int: Optional[int] = Field(default=None)
    day: Optional[List[Day]] = Field(default=None)
