[project]
name = "fatsecret"
version = "1.5.14"
description = "Python wrapper for the Fatsecret API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4",
    "lxml",
    "python-dotenv",
    "rauth==0.7.3",
    "requests==2.32.5",
]

[project.urls]
Documentation = "https://chocotonic.github.io/fatsecret/stable/"
Source = "https://github.com/ChocoTonic/fatsecret"
Issues = "https://github.com/ChocoTonic/fatsecret/issues"
Changelog = "https://github.com/ChocoTonic/fatsecret/releases"

[tool.pytest.ini_options]
pythonpath = ["src"]
markers = ["integration: mark a test as an integration test"]

[dependency-groups]
dev = [
    "black",
    "isort",
    "pytest-cov",
    "pytest",
    "ruff",
    "sphinx-rtd-theme>=3.0.2",
    "sphinx>=7.4.7",
    "pyyaml>=6.0",
]
