#!/usr/bin/env python3
"""Build a static archive of fatsecret docs for every released tag that RTD
does not auto-build (currently anything < v1.4.0).

Output goes to a staging directory (default: ./legacy-staging) laid out as:

    <staging>/legacy/index.html        # top-level listing
    <staging>/legacy/<tag>/index.html  # one tree per tag

The archive is intended to be published to the `gh-pages` branch under
`/legacy/...` so historical users hitting old version-specific URLs land on a
working page rather than a 404.

Design goals:
  * Idempotent: re-running produces the same bytes (no timestamps in output).
  * Tolerant: every tag yields *something*, even if it's a one-line stub.
  * Hermetic: builds happen in `git worktree` checkouts under a temp dir and
    autodoc is disabled so we never import the (often Python-3.11-incompatible)
    old source trees.

Strategy hierarchy per tag:
  A) If `docs/conf.py` exists, run sphinx-build with autodoc/doctest/viewcode
     extensions stripped (-D extensions=) and version/release injected from the
     tag name. This is the preferred path.
  B) On failure (or if docs/ is missing), fall back to a generated stub page
     built from the tag's README, linking to GitHub at the tag and to PyPI.
  C) On total failure, write a minimal one-line stub.
"""

from __future__ import annotations

import argparse
import html
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

# Tags to archive. These are tags that RTD won't auto-build because their
# checkouts either lack `.readthedocs.yaml` entirely (anything pre-PR-#97)
# or carry the broken pre-fix version (v1.3.0 = the merge commit of PR #97
# itself). All v1.4.0+ tags ship with the fixed RTD config and are handled
# by RTD; everything in this list goes to the gh-pages frozen archive.
LEGACY_TAGS: list[str] = [
    # v1.x retroactive tags that predate the RTD config (or carry the
    # broken first version) and therefore can't auto-build on RTD.
    "v1.3.0",
    "v1.2.2",
    "v1.2.1",
    "v1.2.0",
    "v1.1.0",
    "v1.0.2",
    "v1.0.1",
    "v1.0.0",
    # v0.x tags from before the OAS/RTD-era doc layout.
    "v0.15.0",
    "v0.14.0",
    "v0.13.0",
    "v0.12.0",
    "v0.11.0",
    "v0.10.0",
    "v0.9.0",
    "v0.8.0",
    "v0.7.0",
    "v0.6.0",
    "v0.5.1",
    "v0.5.0",
    "v0.4.0",
    "v0.3.0",
    "v0.2.3",
]

REPO_SLUG = "ChocoTonic/fatsecret"  # for GitHub source links
PYPI_PROJECT = "fatsecret"

# Minimal Sphinx pin. Modern Sphinx builds old .rst trees fine as long as we
# disable autodoc so it never tries to import the package.
SPHINX_REQUIREMENTS = ["sphinx==7.4.7", "sphinx-rtd-theme==2.0.0"]


@dataclass
class BuildResult:
    tag: str
    strategy: str  # "sphinx", "stub-readme", "stub-minimal"
    notes: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def run(cmd: list[str], cwd: Path | None = None, check: bool = True, env: dict | None = None) -> subprocess.CompletedProcess:
    print(f"  $ {' '.join(cmd)}", flush=True)
    return subprocess.run(cmd, cwd=cwd, check=check, env=env, capture_output=True, text=True)


def github_url_at_tag(tag: str) -> str:
    return f"https://github.com/{REPO_SLUG}/tree/{tag}"


def pypi_url(tag: str) -> str:
    return f"https://pypi.org/project/{PYPI_PROJECT}/{tag.lstrip('v')}/"


# ---------------------------------------------------------------------------
# Strategy A: Sphinx build with autodoc stripped
# ---------------------------------------------------------------------------


def try_sphinx_build(tag: str, worktree: Path, out_dir: Path, venv_python: Path) -> bool:
    docs_dir = worktree / "docs"
    if not (docs_dir / "conf.py").is_file():
        print(f"  [sphinx] {tag}: no docs/conf.py, skipping strategy A")
        return False

    # Make a sanitized copy of docs/ so we can rewrite conf.py without
    # mutating the worktree (and avoid importing pyproject.toml etc).
    sanitized = worktree.parent / f"{tag}-docs-sanitized"
    if sanitized.exists():
        shutil.rmtree(sanitized)
    shutil.copytree(docs_dir, sanitized)

    # Drop api-spec subtree if present (OpenAPI YAML; not docs source).
    api_spec = sanitized / "api-spec"
    if api_spec.exists():
        shutil.rmtree(api_spec)

    # Replace conf.py with a stripped version (no autodoc, version pinned to tag).
    version_str = tag.lstrip("v")
    short_version = ".".join(version_str.split(".")[:2])
    conf_py = f'''# Generated by scripts/build-legacy-docs/build.py for historical archive of {tag}.
# Original conf.py has been replaced to disable autodoc (which would attempt to
# import the package; old tags are not importable under Python 3.11).
project = "fatsecret"
copyright = "Historical archive"
author = "fatsecret contributors"
release = "{version_str}"
version = "{short_version}"
extensions = []
exclude_patterns = ["_build", "api-spec"]
master_doc = "index"
source_suffix = ".rst"
html_theme = "sphinx_rtd_theme"
html_title = f"fatsecret {{release}} (archived)"
html_show_sphinx = False
'''
    (sanitized / "conf.py").write_text(conf_py)

    # Some old trees have an index.rst that .. include:: contents.rst.inc which
    # tries to use autodoc directives. We let Sphinx render those as plain
    # unknown-directive warnings (non-fatal without -W).
    try:
        run(
            [
                str(venv_python),
                "-m",
                "sphinx",
                "-b",
                "html",
                "-q",  # quiet; we want minimal log noise
                str(sanitized),
                str(out_dir),
            ],
            check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"  [sphinx] {tag}: build FAILED")
        print(e.stdout)
        print(e.stderr)
        return False

    if not (out_dir / "index.html").is_file():
        print(f"  [sphinx] {tag}: no index.html produced")
        return False
    return True


# ---------------------------------------------------------------------------
# Strategy B: README-based stub
# ---------------------------------------------------------------------------


STUB_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>fatsecret {tag} (archived docs)</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 760px; margin: 3em auto; padding: 0 1em; line-height: 1.5; color: #222; }}
  header {{ border-bottom: 1px solid #ddd; padding-bottom: 1em; margin-bottom: 1.5em; }}
  h1 {{ margin: 0; }}
  .subtitle {{ color: #666; margin-top: 0.3em; }}
  pre, code {{ background: #f4f4f4; padding: 0.1em 0.3em; border-radius: 3px; }}
  pre {{ padding: 0.7em; overflow-x: auto; }}
  .note {{ background: #fff8d6; border-left: 3px solid #d4a017; padding: 0.8em 1em; margin: 1.5em 0; }}
  a {{ color: #0366d6; }}
</style>
</head>
<body>
<header>
  <h1>fatsecret {tag}</h1>
  <p class="subtitle">Archived documentation snapshot</p>
</header>
<div class="note">
This is a static archive page for an older release of <code>fatsecret</code>.
For current documentation see <a href="https://fatsecret.readthedocs.io/">fatsecret.readthedocs.io</a>
(auto-built for v1.4.0 and newer). This page is a frozen snapshot for an
older release that RTD does not auto-build, so it links you to the most
useful authoritative sources for this specific version.
</div>

<h2>Resources for {tag}</h2>
<ul>
  <li><a href="{github_url}">Source tree on GitHub at {tag}</a></li>
  <li><a href="{pypi_url}">PyPI release page for {version_str}</a></li>
  <li><a href="../">Back to legacy docs index</a></li>
</ul>

<h2>README at {tag}</h2>
{readme_html}

</body>
</html>
"""


def render_readme_block(worktree: Path) -> str:
    for name in ("README.md", "README.rst", "README.txt", "README"):
        p = worktree / name
        if p.is_file():
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            return f"<pre>{html.escape(text)}</pre>"
    return "<p><em>No README was found at this tag.</em></p>"


def write_stub(tag: str, worktree: Path | None, out_dir: Path, minimal: bool = False) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    version_str = tag.lstrip("v")
    if minimal or worktree is None:
        readme_html = "<p><em>README content was not preserved for this archive entry.</em></p>"
    else:
        readme_html = render_readme_block(worktree)
    page = STUB_TEMPLATE.format(
        tag=html.escape(tag),
        github_url=html.escape(github_url_at_tag(tag)),
        pypi_url=html.escape(pypi_url(tag)),
        version_str=html.escape(version_str),
        readme_html=readme_html,
    )
    (out_dir / "index.html").write_text(page, encoding="utf-8")


# ---------------------------------------------------------------------------
# Top-level index
# ---------------------------------------------------------------------------


INDEX_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>fatsecret legacy documentation archive</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 760px; margin: 3em auto; padding: 0 1em; line-height: 1.5; color: #222; }}
  h1 {{ margin-bottom: 0.2em; }}
  .subtitle {{ color: #666; margin-top: 0; }}
  li {{ margin: 0.3em 0; }}
  .note {{ background: #eef6ff; border-left: 3px solid #0366d6; padding: 0.8em 1em; margin: 1.5em 0; }}
  code {{ background: #f4f4f4; padding: 0.1em 0.3em; border-radius: 3px; }}
</style>
</head>
<body>
<h1>fatsecret legacy documentation</h1>
<p class="subtitle">Frozen archive of docs for releases prior to v1.4.0</p>

<div class="note">
Modern documentation (v1.4.0 and later) lives on Read the Docs:
<a href="https://fatsecret.readthedocs.io/">fatsecret.readthedocs.io</a>.<br>
This archive exists so links to older versions don't 404. It is not maintained.
</div>

<h2>Archived versions</h2>
<ul>
{items}
</ul>
</body>
</html>
"""


def write_top_index(staging_legacy: Path, built: list[BuildResult]) -> None:
    # Sort newest-first by semver-ish key.
    def key(r: BuildResult) -> tuple:
        parts = r.tag.lstrip("v").split(".")
        return tuple(int(p) for p in parts)

    items = "\n".join(
        f'  <li><a href="{html.escape(r.tag)}/">{html.escape(r.tag)}</a>'
        f' <small style="color:#888">[{html.escape(r.strategy)}]</small></li>'
        for r in sorted(built, key=key, reverse=True)
    )
    (staging_legacy / "index.html").write_text(
        INDEX_TEMPLATE.format(items=items), encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def ensure_venv(venv_dir: Path) -> Path:
    """Create an isolated venv with Sphinx pinned. Returns the python binary."""
    if not venv_dir.exists():
        run([sys.executable, "-m", "venv", str(venv_dir)])
    py = venv_dir / "bin" / "python"
    run([str(py), "-m", "pip", "install", "--quiet", "--upgrade", "pip"])
    run([str(py), "-m", "pip", "install", "--quiet", *SPHINX_REQUIREMENTS])
    return py


def add_worktree(repo: Path, tag: str, dest: Path) -> None:
    if dest.exists():
        # Reuse if already populated for the right tag; otherwise nuke.
        shutil.rmtree(dest)
    run(["git", "worktree", "add", "--detach", str(dest), tag], cwd=repo)


def remove_worktree(repo: Path, dest: Path) -> None:
    try:
        run(["git", "worktree", "remove", "--force", str(dest)], cwd=repo, check=False)
    except Exception:
        pass
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)


def build_tag(tag: str, repo: Path, work_root: Path, staging_legacy: Path, venv_python: Path) -> BuildResult:
    print(f"\n== Building {tag} ==")
    worktree = work_root / tag
    out_dir = staging_legacy / tag
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        add_worktree(repo, tag, worktree)
    except subprocess.CalledProcessError as e:
        print(f"  worktree add failed: {e.stderr}")
        write_stub(tag, None, out_dir, minimal=True)
        return BuildResult(tag, "stub-minimal", "worktree add failed")

    try:
        if try_sphinx_build(tag, worktree, out_dir, venv_python):
            return BuildResult(tag, "sphinx")

        print(f"  [stub] {tag}: falling back to README-based stub")
        write_stub(tag, worktree, out_dir, minimal=False)
        return BuildResult(tag, "stub-readme")
    except Exception as e:  # noqa: BLE001
        print(f"  unexpected error for {tag}: {e!r}")
        write_stub(tag, worktree if worktree.exists() else None, out_dir, minimal=worktree is None)
        return BuildResult(tag, "stub-minimal", repr(e))
    finally:
        remove_worktree(repo, worktree)
        sanitized = work_root / f"{tag}-docs-sanitized"
        if sanitized.exists():
            shutil.rmtree(sanitized, ignore_errors=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--staging", type=Path, default=Path("legacy-staging").resolve())
    parser.add_argument("--work-root", type=Path, default=Path(tempfile.gettempdir()) / "fatsecret-legacy-worktrees")
    parser.add_argument("--tags", nargs="*", default=LEGACY_TAGS, help="Override tag list.")
    args = parser.parse_args()

    repo: Path = args.repo.resolve()
    staging: Path = args.staging.resolve()
    work_root: Path = args.work_root.resolve()
    staging_legacy = staging / "legacy"

    staging_legacy.mkdir(parents=True, exist_ok=True)
    work_root.mkdir(parents=True, exist_ok=True)

    venv_dir = work_root / ".venv"
    venv_python = ensure_venv(venv_dir)

    results: list[BuildResult] = []
    for tag in args.tags:
        results.append(build_tag(tag, repo, work_root, staging_legacy, venv_python))

    write_top_index(staging_legacy, results)

    print("\n== Summary ==")
    for r in results:
        extra = f"  ({r.notes})" if r.notes else ""
        print(f"  {r.tag:10s}  {r.strategy}{extra}")
    print(f"\nOutput: {staging_legacy}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
