"""Emit deterministic YAML/Markdown artifacts."""

from __future__ import annotations

import logging
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

from .config import OUT_INVENTORY, OUT_OPENAPI, OUT_RAW_DIR
from .models import EndpointSpec, MethodRef

log = logging.getLogger(__name__)


class _SortedDumper(yaml.SafeDumper):
    pass


def _represent_dict_sorted(dumper: yaml.SafeDumper, data: dict) -> Any:
    return dumper.represent_mapping(
        "tag:yaml.org,2002:map", sorted(data.items(), key=lambda kv: kv[0])
    )


_SortedDumper.add_representer(dict, _represent_dict_sorted)


def _dump_yaml(obj: Any) -> str:
    return yaml.dump(
        obj,
        Dumper=_SortedDumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=100,
    )


def emit_inventory(refs: list[MethodRef], path: Path = OUT_INVENTORY) -> None:
    by_method: dict[str, list[str]] = defaultdict(list)
    for r in refs:
        by_method[r.method].append(r.version)
    lines = [
        "# FatSecret Platform API — Documentation Inventory",
        "",
        "Generated by `scripts/oas-sync`. Do not edit by hand.",
        "",
        f"**Totals: {len(by_method)} unique methods, {len(refs)} (method, version) pairs.**",
        "",
        "| Method | Versions |",
        "|---|---|",
    ]
    for method in sorted(by_method):
        versions = ", ".join(sorted(by_method[method]))
        lines.append(f"| `{method}` | {versions} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("wrote %s", path)


def emit_raw_yaml(
    category: str, specs: list[EndpointSpec], out_dir: Path = OUT_RAW_DIR
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    doc = {
        "endpoints": [
            s.to_dict()
            for s in sorted(specs, key=lambda s: (s.ref.method, s.ref.version))
        ]
    }
    path = out_dir / f"{category}.yaml"
    path.write_text(_dump_yaml(doc), encoding="utf-8")
    log.info("wrote %s (%d endpoints)", path, len(specs))


def emit_openapi(specs: list[EndpointSpec], path: Path = OUT_OPENAPI) -> None:
    """Assemble a minimal but valid OpenAPI 3.1 document.

    Each (method, version) pair becomes one operation. method= endpoints share
    /rest/server.api but are distinguished by an enum-pinned `method` query
    parameter. REST-style endpoints get their own paths.
    """
    paths: dict[str, dict[str, Any]] = {}
    for s in specs:
        if s.rest_url:
            url = s.rest_url
        else:
            url = "/rest/server.api"
        op_method = s.http_verb.lower()
        op_id = s.ref.slug

        params: list[dict[str, Any]] = []
        if s.api_method_param:
            params.append(
                {
                    "name": "method",
                    "in": "query",
                    "required": True,
                    "schema": {"type": "string", "enum": [s.api_method_param]},
                }
            )
        for p in s.parameters:
            params.append(
                {
                    "name": p.name,
                    "in": "query",
                    "required": p.required,
                    "description": p.description,
                    "schema": {"type": (p.type or "string").lower()},
                }
            )

        op = {
            "operationId": op_id,
            "tags": [s.ref.method.split(".")[0]],
            "summary": f"{s.ref.method} ({s.ref.version})",
            "deprecated": s.deprecated,
            "parameters": params,
            "responses": {
                "200": {"description": "OK"},
                "default": {"$ref": "#/components/responses/Error"},
            },
        }
        if s.premier:
            op["x-fatsecret-premier"] = True
        if s.parse_warnings:
            op["x-fatsecret-parse-warnings"] = list(s.parse_warnings)

        paths.setdefault(url, {})[op_method + "_" + op_id] = op

    # Collapse the per-op-id key trick back into proper OpenAPI shape: one
    # verb per (path, method) — but FatSecret puts many ops on the same path
    # & verb, which OpenAPI doesn't natively support. Encode as a list under
    # `x-fatsecret-operations` for the shared path, plus a real entry for the
    # first operation so the file still validates.
    canonical_paths: dict[str, dict[str, Any]] = {}
    for url, op_map in paths.items():
        verb_buckets: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for key, op in op_map.items():
            verb, _ = key.split("_", 1)
            verb_buckets[verb].append(op)
        entry: dict[str, Any] = {}
        for verb, ops in verb_buckets.items():
            primary = ops[0]
            if len(ops) > 1:
                primary["x-fatsecret-additional-operations"] = ops[1:]
            entry[verb] = primary
        canonical_paths[url] = entry

    doc = {
        "openapi": "3.1.0",
        "info": {
            "title": "FatSecret Platform API",
            "version": "2026.01",
            "description": (
                "Community-derived OpenAPI specification for the FatSecret Platform API. "
                "Generated by scripts/oas-sync from platform.fatsecret.com/docs."
            ),
        },
        "servers": [{"url": "https://platform.fatsecret.com"}],
        "components": {
            "securitySchemes": {
                "oauth2": {
                    "type": "oauth2",
                    "flows": {
                        "clientCredentials": {
                            "tokenUrl": "https://oauth.fatsecret.com/connect/token",
                            "scopes": {
                                "basic": "Basic API access",
                                "premier": "Premier tier methods",
                                "barcode": "Barcode lookup",
                                "localization": "Localized results",
                                "nlp": "Natural language processing",
                                "image-recognition": "Image recognition",
                                "feedback": "Feedback submission",
                            },
                        }
                    },
                },
                "oauth1": {
                    "type": "http",
                    "scheme": "oauth",
                    "description": (
                        "OAuth 1.0a, HMAC-SHA1 signing. Three-legged flow for "
                        "profile-scoped endpoints. See "
                        "platform.fatsecret.com/docs/guides/authentication/oauth1."
                    ),
                },
            },
            "responses": {
                "Error": {
                    "description": "FatSecret error envelope",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "error": {
                                        "type": "object",
                                        "properties": {
                                            "code": {"type": "integer"},
                                            "message": {"type": "string"},
                                        },
                                    }
                                },
                            }
                        }
                    },
                }
            },
        },
        "paths": dict(sorted(canonical_paths.items())),
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_dump_yaml(doc), encoding="utf-8")
    log.info("wrote %s", path)
