"""Unofficial authenticated FatSecret member-website integration."""

from .client import FatsecretWebClient
from .errors import (
    FatsecretWebAuthenticationError,
    FatsecretWebError,
    FatsecretWebIdempotencyConflictError,
    FatsecretWebNotFoundError,
    FatsecretWebParseError,
    FatsecretWebRateLimitError,
    FatsecretWebVerificationError,
)
from .models import (
    WebFoodPortion,
    WebFoodPortions,
    WebIngredientWrite,
    WebMealType,
    WebNutrition,
    WebRdiSetting,
    WebRdiUpdate,
    WebRecipeCopyOperation,
    WebRecipeCopyRequest,
    WebRecipeDeleteResult,
    WebRecipeDetail,
    WebRecipeIngredient,
    WebRecipeSummary,
    WebRecipeSummaryNutrition,
    WebRecipeWrite,
)

__all__ = [
    "FatsecretWebAuthenticationError",
    "FatsecretWebClient",
    "FatsecretWebError",
    "FatsecretWebIdempotencyConflictError",
    "FatsecretWebNotFoundError",
    "FatsecretWebParseError",
    "FatsecretWebRateLimitError",
    "FatsecretWebVerificationError",
    "WebFoodPortion",
    "WebFoodPortions",
    "WebIngredientWrite",
    "WebMealType",
    "WebNutrition",
    "WebRdiSetting",
    "WebRdiUpdate",
    "WebRecipeCopyOperation",
    "WebRecipeCopyRequest",
    "WebRecipeDeleteResult",
    "WebRecipeDetail",
    "WebRecipeIngredient",
    "WebRecipeSummary",
    "WebRecipeSummaryNutrition",
    "WebRecipeWrite",
]
