# AUTO-GENERATED by scripts/oas-sync emit-resource Food Classification. Do not edit by hand.
"""Resource wrapper for the OAS ``Food Classification`` tag (generated)."""

from __future__ import annotations

from typing import Any, Optional

from .._base import BaseResource


class ClassificationResource(BaseResource):
    """Resource methods for the OAS `Food Classification` tag (generated)."""

    def brands_get_v1(
        self,
        starts_with: str,
        brand_type: Optional[str] = None,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. food_brands.get (v1). DEPRECATED upstream. Premier-only."""
        params: dict[str, Any] = {"method": "food_brands.get"}
        params["starts_with"] = starts_with
        self._client._set_optional(
            params,
            [
                ("brand_type", brand_type),
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "food_brands", list_key="food_brand")
        return raw

    def brands_get_v2(
        self,
        starts_with: str,
        brand_type: Optional[str] = None,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. food_brands.get (v2). Premier-only."""
        params: dict[str, Any] = {"method": "food_brands.get.v2"}
        params["starts_with"] = starts_with
        self._client._set_optional(
            params,
            [
                ("brand_type", brand_type),
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "food_brands", list_key="food_brand")
        return raw

    def categories_get_v1(
        self,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. food_categories.get (v1). DEPRECATED upstream. Premier-only."""
        params: dict[str, Any] = {"method": "food_categories.get"}
        self._client._set_optional(
            params,
            [
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "food_categories", list_key="food_category")
        return raw

    def categories_get_v2(
        self,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. food_categories.get (v2). Premier-only."""
        params: dict[str, Any] = {"method": "food_categories.get.v2"}
        self._client._set_optional(
            params,
            [
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "food_categories", list_key="food_category")
        return raw

    def sub_categories_get_v1(
        self,
        food_category_id: int,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. food_sub_categories.get (v1). DEPRECATED upstream. Premier-only."""
        params: dict[str, Any] = {"method": "food_sub_categories.get"}
        params["food_category_id"] = food_category_id
        self._client._set_optional(
            params,
            [
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "food_sub_categories", list_key="food_sub_category")
        return raw

    def sub_categories_get_v2(
        self,
        food_category_id: int,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. food_sub_categories.get (v2). Premier-only."""
        params: dict[str, Any] = {"method": "food_sub_categories.get.v2"}
        params["food_category_id"] = food_category_id
        self._client._set_optional(
            params,
            [
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "food_sub_categories", list_key="food_sub_category")
        return raw


__all__ = ["ClassificationResource"]
