# AUTO-GENERATED by scripts/oas-sync emit-resource Feedback. Do not edit by hand.
"""Resource wrapper for the OAS ``Feedback`` tag (generated)."""

from __future__ import annotations

from typing import Any, Optional

from .._base import BaseResource


class FeedbackResource(BaseResource):
    """Resource methods for the OAS `Feedback` tag (generated)."""

    def submit_v1(
        self,
        barcode: int,
        issue_type_id: int,
        external_id: str,
        issue_type: Optional[str] = None,
        notes: Optional[str] = None,
        returned_food_food_id: Optional[int] = None,
        returned_food_serving_id: Optional[int] = None,
        image_file_extension: Optional[str] = None,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> Any:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. feedback (v1). Premier-only."""
        body: dict[str, Any] = {}
        body["barcode"] = barcode
        body["issue_type_id"] = issue_type_id
        body["external_id"] = external_id
        self._client._set_optional(
            body,
            [
                ("issue_type", issue_type),
                ("notes", notes),
                ("returned_food.food_id", returned_food_food_id),
                ("returned_food.serving_id", returned_food_serving_id),
                ("image_file_extension", image_file_extension),
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call({}, url="https://platform.fatsecret.com/rest/feedback/v1", method="POST", json_body=body)
        return payload


__all__ = ["FeedbackResource"]
