# AUTO-GENERATED by scripts/oas-sync emit-resource Saved Meals. Do not edit by hand.
"""Resource wrapper for the OAS ``Saved Meals`` tag (generated)."""

from __future__ import annotations

from typing import Any, Optional

from .._base import BaseResource


class MealsResource(BaseResource):
    """Resource methods for the OAS `Saved Meals` tag (generated)."""

    def create_v1(
        self,
        saved_meal_name: str,
        saved_meal_description: Optional[str] = None,
        meals: Optional[str] = None,
    ) -> Any:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. saved_meal.create (v1). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal.create"}
        params["saved_meal_name"] = saved_meal_name
        self._client._set_optional(
            params,
            [
                ("saved_meal_description", saved_meal_description),
                ("meals", meals),
            ],
        )
        payload = self._client._call(params, method="POST")
        raw = self._client._unwrap(payload, "saved_meal_id")
        return raw

    def delete_v1(
        self,
        saved_meal_id: int,
    ) -> bool:
        """saved_meal.delete (v1). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal.delete"}
        params["saved_meal_id"] = saved_meal_id
        payload = self._client._call(params, method="DELETE")
        return self._client._mutator_success(payload)

    def edit_v1(
        self,
        saved_meal_id: int,
        saved_meal_name: Optional[str] = None,
        saved_meal_description: Optional[str] = None,
        meals: Optional[str] = None,
    ) -> bool:
        """saved_meal.edit (v1). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal.edit"}
        params["saved_meal_id"] = saved_meal_id
        self._client._set_optional(
            params,
            [
                ("saved_meal_name", saved_meal_name),
                ("saved_meal_description", saved_meal_description),
                ("meals", meals),
            ],
        )
        payload = self._client._call(params, method="PUT")
        return self._client._mutator_success(payload)

    def get_v1(
        self,
        meal: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. saved_meals.get (v1). DEPRECATED upstream. Premier-only."""
        params: dict[str, Any] = {"method": "saved_meals.get"}
        self._client._set_optional(
            params,
            [
                ("meal", meal),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "saved_meals", list_key="saved_meal")
        return raw

    def get_v2(
        self,
        meal: Optional[str] = None,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. saved_meals.get (v2). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meals.get.v2"}
        self._client._set_optional(
            params,
            [
                ("meal", meal),
            ],
        )
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "saved_meals", list_key="saved_meal")
        return raw

    def item_add_v1(
        self,
        saved_meal_id: int,
        food_id: int,
        saved_meal_item_name: str,
        serving_id: int,
        number_of_units: float,
    ) -> Any:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. saved_meal_item.add (v1). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal_item.add"}
        params["saved_meal_id"] = saved_meal_id
        params["food_id"] = food_id
        params["saved_meal_item_name"] = saved_meal_item_name
        params["serving_id"] = serving_id
        params["number_of_units"] = number_of_units
        payload = self._client._call(params, method="POST")
        raw = self._client._unwrap(payload, "saved_meal_item_id")
        return raw

    def item_delete_v1(
        self,
        saved_meal_item_id: int,
    ) -> bool:
        """saved_meal_item.delete (v1). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal_item.delete"}
        params["saved_meal_item_id"] = saved_meal_item_id
        payload = self._client._call(params, method="DELETE")
        return self._client._mutator_success(payload)

    def item_edit_v1(
        self,
        saved_meal_item_id: int,
        saved_meal_item_name: Optional[str] = None,
        number_of_units: Optional[float] = None,
    ) -> bool:
        """saved_meal_item.edit (v1). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal_item.edit"}
        params["saved_meal_item_id"] = saved_meal_item_id
        self._client._set_optional(
            params,
            [
                ("saved_meal_item_name", saved_meal_item_name),
                ("number_of_units", number_of_units),
            ],
        )
        payload = self._client._call(params, method="PUT")
        return self._client._mutator_success(payload)

    def items_get_v1(
        self,
        saved_meal_id: int,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. saved_meal_items.get (v1). DEPRECATED upstream. Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal_items.get"}
        params["saved_meal_id"] = saved_meal_id
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "saved_meal_items", list_key="saved_meal_item")
        return raw

    def items_get_v2(
        self,
        saved_meal_id: int,
    ) -> list:
        """No typed model — returns the raw FatSecret response shape. See ``docs/migration-v3.rst`` for details. saved_meal_items.get (v2). Premier-only."""
        params: dict[str, Any] = {"method": "saved_meal_items.get.v2"}
        params["saved_meal_id"] = saved_meal_id
        payload = self._client._call(params)
        raw = self._client._unwrap(payload, "saved_meal_items", list_key="saved_meal_item")
        return raw


__all__ = ["MealsResource"]
