# AUTO-GENERATED by scripts/oas-sync emit-resource Native APIs. Do not edit by hand.
"""Resource wrapper for the OAS ``Native APIs`` tag (generated)."""

from __future__ import annotations

from typing import Any, Optional

from .._base import BaseResource


class NativeResource(BaseResource):
    """Resource methods for the OAS `Native APIs` tag (generated)."""

    def image_recognition_v1(
        self,
        image_b64: str,
        eaten_foods_food_id: int,
        eaten_foods_food_name: str,
        include_food_data: Optional[str] = None,
        eaten_foods: Optional[str] = None,
        eaten_foods_food_brand: Optional[str] = None,
        eaten_foods_serving_description: Optional[str] = None,
        eaten_foods_serving_size: Optional[str] = None,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """image.recognition (v1). Premier-only."""
        body: dict[str, Any] = {}
        body["image_b64"] = image_b64
        body["eaten_foods.food_id"] = eaten_foods_food_id
        body["eaten_foods.food_name"] = eaten_foods_food_name
        self._client._set_optional(
            body,
            [
                ("include_food_data", include_food_data),
                ("eaten_foods", eaten_foods),
                ("eaten_foods.food_brand", eaten_foods_food_brand),
                ("eaten_foods.serving_description", eaten_foods_serving_description),
                ("eaten_foods.serving_size", eaten_foods_serving_size),
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call({}, url="https://platform.fatsecret.com/rest/image-recognition/v1", method="POST", json_body=body)
        return self._client._unwrap(payload, list_key="food_response")

    def image_recognition_v2(
        self,
        image_b64: str,
        eaten_foods_food_id: int,
        eaten_foods_food_name: str,
        include_food_data: Optional[str] = None,
        eaten_foods: Optional[str] = None,
        eaten_foods_food_brand: Optional[str] = None,
        eaten_foods_serving_description: Optional[str] = None,
        eaten_foods_serving_size: Optional[str] = None,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """image.recognition (v2). Premier-only."""
        body: dict[str, Any] = {}
        body["image_b64"] = image_b64
        body["eaten_foods.food_id"] = eaten_foods_food_id
        body["eaten_foods.food_name"] = eaten_foods_food_name
        self._client._set_optional(
            body,
            [
                ("include_food_data", include_food_data),
                ("eaten_foods", eaten_foods),
                ("eaten_foods.food_brand", eaten_foods_food_brand),
                ("eaten_foods.serving_description", eaten_foods_serving_description),
                ("eaten_foods.serving_size", eaten_foods_serving_size),
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call({}, url="https://platform.fatsecret.com/rest/image-recognition/v2", method="POST", json_body=body)
        return self._client._unwrap(payload, list_key="food_response")

    def natural_language_processing_v1(
        self,
        user_input: str,
        eaten_foods_food_id: int,
        eaten_foods_food_name: str,
        include_food_data: Optional[str] = None,
        eaten_foods: Optional[str] = None,
        eaten_foods_food_brand: Optional[str] = None,
        eaten_foods_serving_description: Optional[str] = None,
        eaten_foods_serving_size: Optional[str] = None,
        region: Optional[str] = None,
        language: Optional[str] = None,
    ) -> list:
        """natural.language.processing (v1). Premier-only."""
        body: dict[str, Any] = {}
        body["user_input"] = user_input
        body["eaten_foods.food_id"] = eaten_foods_food_id
        body["eaten_foods.food_name"] = eaten_foods_food_name
        self._client._set_optional(
            body,
            [
                ("include_food_data", include_food_data),
                ("eaten_foods", eaten_foods),
                ("eaten_foods.food_brand", eaten_foods_food_brand),
                ("eaten_foods.serving_description", eaten_foods_serving_description),
                ("eaten_foods.serving_size", eaten_foods_serving_size),
                ("region", region),
                ("language", language),
            ],
        )
        payload = self._client._call({}, url="https://platform.fatsecret.com/rest/natural-language-processing/v1", method="POST", json_body=body)
        return self._client._unwrap(payload, list_key="food_response")


__all__ = ["NativeResource"]
