name: Tests

on:
    push:
    pull_request:

concurrency:
    group: fatsecret-tests
    cancel-in-progress: false # ensures one workflow at a time, no cancellation

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            FATSECRET_CONSUMER_KEY: ${{ secrets.FATSECRET_CONSUMER_KEY }}
            FATSECRET_CONSUMER_SECRET: ${{ secrets.FATSECRET_CONSUMER_SECRET }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.9"

            - name: Install uv and dependencies
              run: |
                  pip install uv
                  uv sync --all-extras

            # - name: Run lint
            #   run: make lint

            - name: Run tests (with coverage)
              run: make test

            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                  name: coverage.xml
                  path: coverage.xml
