name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: ["**"]

concurrency:
  group: fatsecret-tests
  cancel-in-progress: false

jobs:
  test-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test-type: 'unit'

  test-master:
    if: github.event_name == 'push'
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test-type: 'all'
