name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: ["**"]

concurrency:
  group: fatsecret-tests
  cancel-in-progress: false

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test-type: ${{ github.event_name == 'pull_request' && 'unit' || 'all' }}
