name: Deploy Sphinx Docs to GitHub Pages

on:
    push:
        branches:
            - master
    pull_request:
        branches: ["**"]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"
            - name: Install uv
              run: pip install uv
            - name: Install dependencies
              run: uv sync --all-extras
            - name: Build Sphinx docs
              run: make docs
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "docs/_build/html"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
            - name: Print deployment URL
              run: |
                  echo "Documentation will be published at: https://$GITHUB_REPOSITORY.github.io/$(basename $GITHUB_REPOSITORY)/"
